<?php

namespace Plugin\TestPlugin\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Plugin\TestPlugin\Entity\Config;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @param string $key
     *
     * @return null|Config
     */
    public function getByKey($key)
    {
        return $this->findOneBy(['configKey' => $key]);
    }

    /**
     * @param string $key
     *
     * @return null|string
     */
    public function getValueByKey($key)
    {
        /** @var Config $config */
        $config = $this->findOneBy(['configKey' => $key]);

        return $config ? $config->getConfigValue() : null;
    }

    /**
     * @param string $key
     * @param string $value
     */
    public function set($key, $value)
    {
        if ($value === null) {
            $value = '';
        }

        if (is_bool($value)) {
            $value = $value ? '1' : '0';
        }

        $config = $this->getByKey($key);
        if (!$config) {
            $config = new Config();
            $config->setConfigKey($key);
        }

        $config->setConfigValue((string) $value);
        $this->save($config);
    }
}
